### ISSUE TITLE
更新方式

### ISSUE THREAD

**Issue by islercn** [chenhw2/luci-app-aliddns#10]
不知道有没有考虑过相应接口ifup来更新？比10分钟一次来得快多了

在/etc/hotplug.d/iface/下创建更新脚本：

if [ "$ACTION"=ifup -a "$INTERFACE"=wan ]; then
    /usr/sbin/aliddns
fi

家里iptv的路由就是这么更新的，一直没发现什么问题

**Comment by chenhw2** [comment]
可以再把这个触发更新添加进去
