### ISSUE TITLE
安装依赖库之后运行错误

### ISSUE THREAD

**Issue by michaelauto** [chenhw2/luci-app-aliddns#2]
openssl-util及curl均已安装，运行后出现以下错误
2017-09-14 01:36:00 WAN-IP: ****
2017-09-14 01:36:00 DOMAIN-IP: 
2017-09-14 01:36:00 UPDATING...
Error relocating /usr/bin/openssl: COMP_zlib_cleanup: symbol not found
Error relocating /usr/bin/openssl: COMP_zlib_cleanup: symbol not found
Error relocating /usr/bin/openssl: BIO_f_zlib: symbol not found
Error relocating /usr/bin/openssl: BIO_f_zlib: symbol not found
sh: write error: Broken pipe
Error relocating /usr/bin/openssl: COMP_zlib_cleanup: symbol not found
Error relocating /usr/bin/openssl: COMP_zlib_cleanup: symbol not found
Error relocating /usr/bin/openssl: BIO_f_zlib: symbol not found
Error relocating /usr/bin/openssl: BIO_f_zlib: symbol not found
sh: write error: Broken pipe
2017-09-14 01:36:00 ADD record 
2017-09-14 01:36:00 # ERROR, Please Check Config/Time！

**Comment by chenhw2** [comment]
x86 or x64?

**Comment by michaelauto** [comment]
ramips-mt7621
and I get the SDK for mt7621 then rebuild one
it shows:
2017-09-14 02:45:21 WAN-IP: *****
2017-09-14 02:45:44 WAN-IP: *****
2017-09-14 02:45:45 WAN-IP: *****
2017-09-14 02:46:00 WAN-IP: ******
nothing happened

**Comment by chenhw2** [comment]
```openssl``` may crash sometimes.
