### ISSUE TITLE
能通过访问一个地址获取ip地址吗？

### ISSUE THREAD

**Issue by gelandesprung** [chenhw2/luci-app-aliddns#4]
二级路由获取不到ip地址，有没有参数可以设置从http://whatismyip.akamai.com/取Ip地址。

**Comment by gelandesprung** [comment]
原来这个是脚本啊，把/usr/sbin/aliddns文件打开，修改一下ip的获取方法就行了。作者把从网络上获取的方法注释掉了。

**Comment by chenhw2** [comment]
待添加这个选项
