### ISSUE TITLE
无法使用uci配置

### ISSUE THREAD

**Issue by islercn** [chenhw2/luci-app-aliddns#9]
之前 [issue 3](https://github.com/chenhw2/luci-app-aliddns/issues/3) 里有人说出错，提示配置文件错误。

我发现如果使用uci配置，那肯定无法生效，必须去luci中取消启用、应用，再重新启用。

另外，uci配置后的配置文件内容和重新启用后内容是一样的。

uci set aliddns.base.time="10"
uci set aliddns.base.app_key="xxxxx"
uci set aliddns.base.app_secret="xxxxxxxxxx"
uci set aliddns.base.interface="wan"
uci set aliddns.base.main_domain="xxxxx.com"
uci set aliddns.base.sub_domain="xxxxx"
uci set aliddns.base.clean="1"
uci set aliddns.base.enable="1"
uci commit aliddns
/etc/init.d/aliddns restart

**Comment by chenhw2** [comment]
```uci commit aliddns```
之后 直接 运行这个命令试试
```/usr/sbin/aliddns```

**Comment by chenhw2** [comment]
一些反馈?

**Comment by islercn** [comment]
貌似可以了😁

**Comment by chenhw2** [comment]
应该是```/etc/init.d/aliddns restart```并不会直接去启动aliddns, 只是添加了定时任务(10分钟一次)， 你去看log看太早了
